export default [
    {
        id: "sor-1",
class: "sorprise",
        question:'VISIÓN DE LOS OTROS (ESCUCHA)',
    title: "sorpresa", 
},
    {
        id: "sor-2",
class: "sorprise",
        question:'DEFIENDE EL PUNTO DE VISTA OPUESTO',
    title: "sorpresa", 
},
    {
        id: "sor-3",
class: "sorprise",
        question:'DOBLA LA APUESTA: ¿QUÉ PROPONES?',
    title: "sorpresa", 
},
    {
        id: "sor-4",
class: "sorprise",
        question:'TU VIDA EN JUEGO: ¿QUÉ HARÍAS?',
    title: "sorpresa", 
},
    {
        id: "sor-5",
class: "sorprise",
        question:'BUSCA TRES ALTERNATIVAS POSIBLES Y VALIDAS PARA LOGRAR LO QUE QUIERES DIFERENTES A LAS QUE YA HAS CONTEMPLADO',
    title: "sorpresa", 
},
    {
        id: "sor-6",
class: "sorprise",
        question:'INVIERTE EL ESCENARIO: ¿SI TU FUERAS EL OTRO, COMO TE VERÍAS?',
    title: "sorpresa", 
},
    {
        id: "sor-7",
class: "sorprise",
        question:'PEOR ESCENARIO: ¿QUE ES LO PEOR QUE TE PUEDE PASAR SI TODO SALE MAL? (TRAGARSE UN SAPO)',
    title: "sorpresa", 
},
    {
        id: "sor-8",
class: "sorprise",
        question:'¿SI EL DESTINO TE DIERA UNA SOPRESA, CUÁL SERIA?',
    title: "sorpresa", 
},
    {
        id: "sor-9",
class: "sorprise",
        question:'¿QUIERES LOGRARLO O QUIERES TENER RAZÓN?',
    title: "sorpresa", 
},
    {
        id: "sor-10",
class: "sorprise",
        question:'SI JUGARAS GANAR GANAR…SI JUGARAS PARA NO PERDER…SI JUGARAS PARA PERDER…',
    title: "sorpresa", 
},
    {
        id: "sor-11",
class: "sorprise",
        question:'¿Qué aprendizaje hay en esta situación?',
    title: "sorpresa", 
},
    {
        id: "sor-12",
class: "sorprise",
        question:'¿Identifica una persona que tenga valor en tu vida: cuál será el legado para el/ella una vez que lo logres.',
    title: "sorpresa", 
},
    {
        id: "sor-13",
class: "sorprise",
        question:'¿En qué no has pensado aún?',
    title: "sorpresa", 
},
    {
        id: "sor-14",
class: "sorprise",
        question:'¿Cuál sería un resultado inesperado?',
    title: "sorpresa", 
},
    {
        id: "sor-15",
class: "sorprise",
        question:'Dibuja el resultado',
    title: "sorpresa", 
},
    {
        id: "sor-16",
class: "sorprise",
        question:'Identifica dos bloqueos. Transfórmalos en oportunidad',
    title: "sorpresa", 
},
    {
        id: "sor-17",
class: "sorprise",
        question:'¿Si fuera una canción, cuál representa tu situación (actual/deseada)?',
    title: "sorpresa", 
},
    {
        id: "sor-18",
class: "sorprise",
        question:'¿Si fuera una película, cuál representa tu situación (actual/deseada)?',
    title: "sorpresa", 
},
    {
        id: "sor-19",
class: "sorprise",
        question:'¿Si pudieras pedir tres deseos, cuáles serían?',
    title: "sorpresa", 
},
    {
        id: "sor-20",
class: "sorprise",
        question:'Toma una carta de decisión y haz lo que te dice',
    title: "sorpresa", 
},
    {
        id: "sor-21",
class: "sorprise",
        question:'¿Pregúntale al jugador de la derecha qué haría en esta situación?',
    title: "sorpresa", 
},
    {
        id: "sor-22",
class: "sorprise",
        question:'¿Si un niño tuviera la respuesta, qué te diría?',
    title: "sorpresa", 
},
    {
        id: "sor-23",
class: "sorprise",
        question:'Consigue la respuesta de un niño',
    title: "sorpresa", 
},
    {
        id: "sor-24",
class: "sorprise",
        question:'¿Qué pregunta no te has hecho todavía?',
    title: "sorpresa", 
},
]